filebeat.inputs:
  - type: filestream
    id: docker-containers
    enabled: true
    paths:
      - /var/lib/docker/containers/*/*-json.log

    parsers:
      - ndjson:
          target: ""
          message_key: "log"

    processors:
      - decode_json_fields:
          fields: ["message"]
          target: ""
          overwrite_keys: true
          add_error_key: true

      - rename:
          fields:
            - from: "event"
              to: "pino.event"
          ignore_missing: true
          fail_on_error: false

      - add_docker_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]
