/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Tournament } from "./Tournament";
export * as factories from "./factories";
export { Tournament__factory } from "./factories/Tournament__factory";
